### ISSUE TITLE
Email members in an equipment list using a button

### ISSUE THREAD

**Issue by harvy4002** [HACManchester/membership-system#116]
We have a need to email lists of members in particular ones waiting for inductions, say around the 3d printer or laser cutter. Or even to notify members of outages or practice changes.

The idea is to be able to email members tied to particular piece of equipment through the member portal pages.

Here we have a list of members awaiting induction. It would be great if there was a button that popped up a modal where I could enter a message and then it would send an email to those members in that list. 
![image](https://user-images.githubusercontent.com/992801/199334356-32aaa0e0-9c12-4c50-a957-013438b617e9.png)

The email should be templated to contain: why they are being sent that email (most likely as they are in a list) and who it came from (tied to the account that triggered it)

It should only be that maintainers and trainers can only send the messages (the list on the left)
![image](https://user-images.githubusercontent.com/992801/199335009-ceea397d-75aa-4f23-900e-1ebaf933e910.png)

**Comment by rjackson** [comment]
Couple questions to help this request:

1. What list of members does this refer to? All members? Members of a team?
2. What would the emails be for?
3. Who should be able to send emails (team members? equipment trainers? anybody?

Without knowing any detail, I'd be cautious about any sort of unrestricted direct-to-member email functionality due to possible spam/abuse risk. If that is the desire it may be preferable to build an on-site messaging system instead, or direct people to contact members via our Telegram groups.

**Comment by harvy4002** [comment]
Sorry I just left this as a placeholder. Description updated

**Comment by rjackson** [comment]
That's great, I'm happy to take a look at this :)

We do appear to have some functionality like this through [NotificationEmailController](https://github.com/HACManchester/membership-system/blob/master/app/Http/Controllers/NotificationEmailController.php), but it looks like it's limited to emailing either all members, or "laser_induction_members" – which appears to be those already trained. I don't think it's worth extending any of this functionality, though, cause it'll very quickly grow into an unmaintainable mess of concerns.

Instead I'm thinking of introducing the concept of "Equipment emails" to the system, for contacting folks with a relationship to a piece of equipment – whether they're maintainers, trained users, or inductees; and doing so in a way that can be re-used for all pieces of equipment. I've got a good idea of how to put that into place. Hopefully I'll have something to show over the next week or so :)
