### ISSUE TITLE
Adding new equipment issues

### ISSUE THREAD

**Issue by harvy4002** [HACManchester/membership-system#133]
There are a few issues to adding new equipement. I have spotted:

- You need to be an admin to add new equipment as there are no trainers role for that equipement. There should be a way to handle that? Maybe certain users can be given a role that lets them setup new equipement and delegate trainers as part of equipment setup.
- Users shouldn't see the button to add new equipment if they don't have permissions
- Some fields fail validation but it's not clear which without looking at the logs. These are: "requires induction" field needs admin permission, access fee or some value needs to be filled in.

**Comment by rjackson** [comment]
> Some fields fail validation but it's not clear which without looking at the logs. These are: "requires induction" field needs admin permission, access fee or some value needs to be filled in.

Fixed this one.

Will have to look into the issues of non-admins not being able to create new pieces of equipment, although I could understand an argument to restrict equipment creation.
