### ISSUE TITLE
Access Fee is not visible on the equipment page

### ISSUE THREAD

**Issue by harvy4002** [HACManchester/membership-system#135]
It seems the access fee is not visible on the equipment page, so users could be charged without knowing.

Also can a confirmation box be put up so that a user know by requesting a induction they will be charged the access fee of : £X, as I assume most wouldn't read the page anyway.

**Comment by rjackson** [comment]
I don't think this is correct. We show the following form for users requesting training, and they have to choose "Pay induction fee" when requesting their training.

![image](https://github.com/HACManchester/membership-system/assets/602850/22ceed5d-1369-472c-ad8c-5e7a4422bc3d)

**Comment by harvy4002** [comment]
I guess I just don't see that as already trained member.
Is there a test account I can use in the future to check what pages look like for new members? 
Happy for this to be closed in the meantime.
