### ISSUE TITLE
Mark equipment as not taking any more members

### ISSUE THREAD

**Issue by harvy4002** [HACManchester/membership-system#136]
This is a use case where a piece of equipment will still be in use by current members but we will no longer be inducting new members.
It's a temporary measure as we migrate people to new equipment.

**Comment by rjackson** [comment]
Added a new "Accepting induction requests" field to equipment

![image](https://github.com/HACManchester/membership-system/assets/602850/99440cbd-3e06-459c-8d6f-c0273b500b30)
